version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: rp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: recruitment_portal
      MYSQL_USER: recruitment_user
      MYSQL_PASSWORD: recruitment_pass
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rp-backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: recruitment_portal
      DB_USER: recruitment_user
      DB_PASSWORD: recruitment_pass
      DB_CONN_LIMIT: 10
      JWT_SECRET: supersecretchangeme
      JWT_EXPIRES_IN: 1d
      UPLOAD_DIR: /data/uploads
      MAX_UPLOAD_MB: 10
      CORS_ORIGIN: http://localhost:5173
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 100
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '4000:4000'
    volumes:
      - uploads-data:/data/uploads
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rp-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    ports:
      - '5173:80'
    depends_on:
      - backend
volumes:
  db-data:
  uploads-data: